
# SPRING
spring:
  # DATA SOURCE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.15.218:3306/exampie?serverTimezone=UTC
    username: qiong
    password: qiong
    type: com.alibaba.druid.pool.DruidDataSource
  # REDIS
  redis:
    host: 42.192.15.218 #localhost #
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        max-active: 8

# MYBATIS
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Dao.xml

# LOG
logging:
  level:
    root: error

server:
  port: 80
